services:
  db:
    image: postgres:15
    container_name: parseflow_db
    restart: always
    environment:
      POSTGRES_DB: parseflow_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - parseflow_net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parseflow_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: parseflow_db
    depends_on:
      - db
    networks:
      - parseflow_net

  # 🧪 NOVO serviço de testes
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: parseflow_tests
    volumes:
      - .:/app
    entrypoint: ["/bin/sh", "-c"]
    command:
      - >
        go test ./... -v -coverprofile=cover.out &&
        go tool cover -html=cover.out -o cover.html &&
        echo '✅ Testes rodados e cobertura gerada em cover.html'
    networks:
      - parseflow_net

volumes:
  postgres_data:

networks:
  parseflow_net:
