version: '3.8'

services:
  db:
    image: postgres:15
    container_name: parseflow_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: parseflow_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: parseflow_app
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: parseflow_db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    working_dir: /app
    command: ["./parseflow"]

volumes:
  db_data:
