services:
  db:
    image: postgres:15
    container_name: parseflow_db
    restart: always
    environment:
      POSTGRES_DB: parseflow_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - parseflow_net

  app:
    build: .
    container_name: parseflow_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: parseflow_db
    depends_on:
      - db
    networks:
      - parseflow_net

volumes:
  postgres_data:

networks:
  parseflow_net:
